# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=35, unique=True, verbose_name='ID письма')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('url', models.URLField(verbose_name='url письма')),
                ('key', models.CharField(max_length=250, verbose_name='storage key')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Письма',
                'verbose_name': 'Письмо',
            },
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Дата события')),
                ('event', models.CharField(choices=[('accepted', 'Принято'), ('failed', 'Неудачно'), ('rejected', 'Отклонено'), ('delivered', 'Доставлено'), ('complained', 'Спам'), ('stored', 'Входящее')], max_length=20, verbose_name='Событие')),
                ('event_id', models.CharField(max_length=30, unique=True, verbose_name='ID события')),
                ('failed_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус неудачного')),
                ('log_level', models.CharField(choices=[('info', 'green'), ('warm', 'yellow'), ('error', 'red')], max_length=5, verbose_name='Уровень лога')),
                ('delivery_code', models.IntegerField(blank=True, null=True, verbose_name='Код доставки')),
                ('delivery_message', models.CharField(blank=True, max_length=250, null=True, verbose_name='Сообщение доставки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_library.Message', verbose_name='Письмо')),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'Событие',
                'ordering': ('-time', '-event'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake', models.BooleanField(default=False, verbose_name='Некорректная почта')),
                ('reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='Причина')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
                'verbose_name': 'Профиль пользователя',
            },
        ),
    ]
